### ISSUE TITLE
Cannot login on Android 11

### ISSUE THREAD

**Issue by il-santo** [Livinglist/Hacki#58] opened 2022-06-22 05:53 UTC
I have several devices with Android 11 and when I try to login to my Hacker News account the app keeps loading and never succeeds to gain access to it.
![Screenshot_2022-06-22-07-50-29-671_com.jiaqifeng.hacki.jpg](https://user-images.githubusercontent.com/1225817/174953716-bf47c2da-ac34-4ca7-8c84-02504865ca33.jpg)

**Comment by Livinglist** [comment] 2022-06-22 07:21
Hi @il-santo , thanks for reporting the issue. Can you tell me which version of the app are you on? Thx! (You can check the version number in settings by tapping on “About”.

at the same time, you can try logging in over other networks  try using cellular data instead of Wi-Fi)

**Comment by il-santo** [comment] 2022-06-22 07:28
I tried all versions since the introduction of the login feature until the last one (0.2.21). I tried both on WiFi and on cellular data.

**Comment by Livinglist** [comment] 2022-06-22 08:49
This might be related https://github.com/mogol/flutter_secure_storage/issues/363

**Comment by Livinglist** [comment] 2022-06-23 07:24
v0.2.22 just got released and hopefully fixed this issue. As I’m not quite sure the exact cause since I don’t have a android device to debug on, I suspect this is caused by https://github.com/mogol/flutter_secure_storage/issues/13#issuecomment-421083742

**Comment by il-santo** [comment] 2022-06-23 08:42
Without uninstalling the app, it still doesn't work. And the bug remains even if I uninstall it. Sorry!

**Comment by Livinglist** [comment] 2022-06-23 15:49
@il-santo is your system backup feature turned on?

**Comment by il-santo** [comment] 2022-06-23 16:53
Yes, but I just verified that there is no backup for Hacki.

**Comment by Livinglist** [comment] 2022-06-24 02:43
@il-santo Just released v0.2.23 with a fix for infinite loading, hopefully this time it works.

**Comment by il-santo** [comment] 2022-06-24 05:48
@Livinglist , it's still not working. :-(
Maybe later I will provide you with a logcat, if I can find the time and I remember to do it...

**Comment by Livinglist** [comment] 2022-06-24 05:53
@il-santo  😢 mission failed, we will get em next time.

**Comment by il-santo** [comment] 2022-06-24 11:16
@Livinglist I tried to investigate further but logcat really doesn't show anything useful. No errors, no warnings, no timeouts. Sorry.

**Comment by lead0r** [comment] 2023-04-01 10:32
I'm on Android 12 and I have the same problem. I am using Hacki 1.3.3 (newest version from F-Droid)

**Comment by Livinglist** [comment] 2023-04-01 16:23
@lead0r hi there! Can you try logging in then go to settings, scroll to bottom, tap on About and then tap on Report Issue, select Email which will send an email to me with your logs attached or select GitHub which will save the log file to your local storage. This will greatly help with debugging!

**Comment by lead0r** [comment] 2023-04-01 16:34
> @lead0r hi there! Can you try logging in then go to settings, scroll to bottom, tap on About and then tap on Report Issue, select Email which will send an email to me with your logs attached or select GitHub which will save the log file to your local storage. This will greatly help with debugging!
> 
> Also can you try logging in Hacker News in a browser using the same account on the same network you were using to see if your account requires CAPTCHA on logging in?

Done. And on the same network in a browser successfully logged in without any captcha

**Comment by Livinglist** [comment] 2023-04-01 16:42
@lead0r thanks! Does your user have any activity on Hacker News before? Trying to confirm something cuz I just saw this from HN‘s api doc: 

`Users are identified by case-sensitive ids, and live under /v0/user/. Only users that have public activity (comments or story submissions) on the site are available through the API`

**Comment by lead0r** [comment] 2023-04-01 16:44
@Livinglist oh, okay. I've had this account for a while but only for upvoting etc. I could post a comment and see if I can log in if that helps?

**Comment by Livinglist** [comment] 2023-04-01 16:45
@lead0r that would be really helpful!

**Comment by lead0r** [comment] 2023-04-01 16:51
@Livinglist well, that was easy :D I posted a comment in a browser and when I opened Hacki afterwards, I was already logged in. Thank you!

**Comment by Livinglist** [comment] 2023-04-01 16:57
> @Livinglist well, that was easy :D I posted a comment in a browser and when I opened Hacki afterwards, I was already logged in. Thank you!

No problem! I will have a fix merged today.

**Closed** 2023-04-01 17:07 UTC
Labels: bug, android
